language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Construct the environment
  - echo "$TRAVIS_PYTHON_VERSION"
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda env create -f environment_27.yml
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda env create -f environment_35.yml
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda env create -f environment_36.yml
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      conda env create -f environment_37.yml
    else
      echo "Unknown python version $TRAVIS_PYTHON_VERSION"
    fi
  - conda activate pycbc-examples-env
  - python setup.py install

script: pytest # run tests
after_success:
  - codecov # submit coverage
