name: pycbc-examples-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pytest
  - codecov
  - pycbc
  - jupyter
  - jupyter_contrib_nbextensions
  - pip:
      - gravtools >= 0.1.2